### ISSUE TITLE
Compatible Drawer Builders?

### ISSUE THREAD

**Issue by searchy2** [yarolegovich/SlidingRootNav#10]
This library does not provide the user with drawer builders. What drawer builders would you suggest or are compatible with this library? Would you suggest just building your own using RecyclerView? Thank you!

**Comment by yarolegovich** [comment]
The only drawer builder I've ever used is [MaterialDrawer](https://github.com/mikepenz/MaterialDrawer) and it is an awesome library. AFAIK it has a method to get drawer as a View and not to inject it, so I'm pretty sure you can combine it with SlidingRootNav.

**Comment by searchy2** [comment]
@yarolegovich Thanks for the quick response! I have come across MaterialDrawer before and thought it was too complex haha. Great for keeping in line with Material Design standards but MD is so ugly :P 
I really love this library and especially your design approach. Thank you so much for not bundling your own drawer implementation and providing essentially a blank canvas to work with. I am going to develop my own drawer layout with some pretty extreme customizations. 

I'm thinking about a large profile picture surrounded with particles from https://github.com/Doctoror/ParticlesDrawable
And then maybe a background with procedurally generated triangles from https://github.com/Oyzuu/PatternPlaceholder-Android

The possibilities are endless!

**Comment by yarolegovich** [comment]
Cool libraries.
I thought that if a developer uses my library, the design will probably be unusual and it will be extremely hard to provide a flexible enough builder to satisfy all the possible customizations.

**Comment by searchy2** [comment]
God bless this library! This is amazing:
![Sliding Nav Menu Particles]
(https://cloud.githubusercontent.com/assets/19896174/25930046/6f2fbf1e-35c9-11e7-83c9-ea9a6194ee37.gif)
The particles make a really nice background! The way they ooze onto the screen from the edges is so zen. 

For anyone who wishes to make this effect, just use a frame layout for the menu_left_drawer.xml, Also, the particles effect uses around 20% CPU on the Snapdragon 820 and drains a bit of battery. Set the particle view visibility to GONE when the slide drawer is not open to save battery!

**Comment by searchy2** [comment]
Posted on MaterialUp: 
https://material.uplabs.com/posts/particle-navigation-drawer-interface
