### ISSUE TITLE
How to access views

### ISSUE THREAD

**Issue by bahramnooraii** [yarolegovich/SlidingRootNav#12]
Hi, thanks for this great library.
How can i access views of into **menu_left_drawer.xml** from main activity?
For example : i want change text in menu.
i use this code in main activity but show me nullPointer error :
```
            txt = (TextView) findViewById(R.id.menuHeaderText);
            txt.setText("tr");
```

**Comment by searchy2** [comment]
I had this problem as well. What I find works is if you declare the SlidingRootNavBuilder and inject it before acessing views. Put the code for the builder before the code accessing items in the builder.

Here:
`        new SlidingRootNavBuilder(this)
                .addDragListener(dragListener)
                .withSavedState(savedInstanceState)
                .withMenuLayout(R.layout.menu_left_drawer)
                .inject();
         txt = (TextView) findViewById(R.id.menuHeaderText);
            txt.setText("tr");

` 
Hope this helps!

**Comment by yarolegovich** [comment]
@searchy2 is correct, views appear in your layout after a call to `inject`.
