### ISSUE TITLE
Add root view background option

### ISSUE THREAD

**Issue by Ekalips** [yarolegovich/SlidingRootNav#15]
Please, add ability to set root view background from Drawable or Drawable resource

**Comment by yarolegovich** [comment]
You can set it in your either in xml layout or in code. That's completely not related to the library.

**Comment by Ekalips** [comment]
I think it's misunderstanding. Yes, you can set background of activity (which would not be applied to "menu background"), or window background (with theme). So in the case when you want to always have same theme you can't change menu (view behind activity) background. And I'm asking for adding something like ImageView behind both activity and menu as a background.

**Comment by yarolegovich** [comment]
Why you can't just set menu background?
