### ISSUE TITLE
How to close the drawer on item click

### ISSUE THREAD

**Issue by gssinghgautam** [yarolegovich/SlidingRootNav#2]
How can close the drawer whenever a item in drawer is clicked

**Comment by yarolegovich** [comment]
`inject()` method returns you an object that implements `SlidingRootNav` and has a method `closeMenu()`. Call it in your item click listener.

**Comment by gssinghgautam** [comment]
Hey yarolegovich  thanks man,
this is how i am closing the drawer on click
if (slidingRootNavLayout!=null && !slidingRootNavLayout.isMenuHidden()){
            slidingRootNavLayout.closeMenu();
 }

**Comment by yarolegovich** [comment]
Yeah, correct. Hope it works for you.

**Comment by devlovepreet** [comment]
@gssinghgautam  @yarolegovich  can you please tell the exact code to close the drawer on item click ? I tried implementing the above code in sampleActivity, but it didn't work. Please tell me exactly where to include this code. Thanks.

**Comment by monikarora** [comment]
@devlovepreet  
define   SlidingRootNav menu;
// oncreate 
  menu = new SlidingRootNavBuilder(this)
                .withToolbarMenuToggle(toolbar)
                .withMenuOpened(false)
                .withMenuLayout(id)
                .withSavedState(savedInstanceState)
                .withMenuLayout(R.layout.activity_drawer_item)
                .inject();

//itemclicklistener
menu.close

**Comment by abhishekengineer** [comment]
my itemclicklistener is in Recyclerview adapter, what should i do
