### ISSUE TITLE
Elevation not working

### ISSUE THREAD

**Issue by Bunty007** [yarolegovich/SlidingRootNav#20]
As soon as customer opens the drawer , its elevation should get increased, but its not showing any elevation.

**Comment by bowiechang** [comment]
hi can i know which code are u inputting to increase elevation? By elevation do u mean the shadow?

**Comment by yarolegovich** [comment]
I guess you are testing on a pre-Lollipop device. It's not supposed to work on lower android versions.

**Comment by deviant-studio** [comment]
same issue. no shadow on 7.1 device (nexus 5)
