### ISSUE TITLE
how to use Expandable listview instead of Listview

### ISSUE THREAD

**Issue by Mohsin92** [yarolegovich/SlidingRootNav#23]
Can you please give me hint for how to use Expandable List View ?

**Comment by ZeroCool00** [comment]
did you get any solution with this library.

**Comment by yarolegovich** [comment]
Sure, the hint is to use expandable ListView implementation. 
Again, the library doesn't provide any menu builders. [The sample](https://github.com/yarolegovich/SlidingRootNav/tree/master/sample) shows how to create a [menu](https://github.com/yarolegovich/SlidingRootNav/blob/master/sample/src/main/res/layout/menu_left_drawer.xml) using a `RecyclerView`, and you should do the same, just with something that supports expandable list items ([suggestion](https://github.com/h6ah4i/android-advancedrecyclerview)).
