### ISSUE TITLE
Not useable with Arabic language

### ISSUE THREAD

**Issue by kulvinder18may** [yarolegovich/SlidingRootNav#25]
If i selected Arabic language from my device then drawer open/close not working...otherwise working great. Can you please fix it for that

**Comment by AniketBito** [comment]
It works with Arabic language. Just set SlideGravity.RIGHT when language is arabic and SlideGravity.LEFT when English.

.withGravity(SlideGravity.RIGHT)

**Comment by yarolegovich** [comment]
A duplicate of #35
