### ISSUE TITLE
.withMenuOpened(false) dont work

### ISSUE THREAD

**Issue by Sadwyn** [yarolegovich/SlidingRootNav#3]
If i want to disable instant open drawer, I cant do this. Drawer always starts opened, just toggle changes from arrow to hamburger, but drawer stay still opened. Is there any solution about this, or it will be fixed in next version of library? Thanks

**Comment by yarolegovich** [comment]
Thanks a lot, I misused my own API. Will fix it now.

**Comment by yarolegovich** [comment]
Use the version 1.0.2, everything will work now.
