### ISSUE TITLE
Content is clickable when open menu

### ISSUE THREAD

**Issue by rahulabrol** [yarolegovich/SlidingRootNav#32]
"withContentClickableWhenMenuOpened" not working

**Comment by yarolegovich** [comment]
Where do you handle clicks?

**Comment by XeRrIc** [comment]
new SlidingRootNavBuilder(this)
  .withMenuOpened(true) //Initial menu opened/closed state. Default == false
  .withMenuLocked(false) //If true, a user can't open or close the menu. Default == false.
  .withGravity(SlideGravity.LEFT) //If LEFT you can swipe a menu from left to right, if RIGHT - the direction is opposite. 
  .withSavedState(savedInstanceState) //If you call the method, layout will restore its opened/closed state
  **.withContentClickableWhenMenuOpened(isClickable)**

make this false
