### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by AniketBito** [yarolegovich/SlidingRootNav#33]
It doesn't support RTL

**Comment by WiiliamChik** [comment]
same question.

**Comment by WiiliamChik** [comment]
i found the solution. SlidingRootNav supports rtl. just add the code in the SlidingRootNavBuilder.

`public SlidingRootNavBuilder(Activity activity) {
        this.activity = activity;
        this.transformations = new ArrayList<>();
        this.dragListeners = new ArrayList<>();
        this.dragStateListeners = new ArrayList<>();
        this.gravity = OSUtil.isRTL() ? SlideGravity.RIGHT : SlideGravity.LEFT; //  insert this line to support rtl, OSUtil.isRTL() is my custom function.
        this.dragDistance = dpToPx(DEFAULT_DRAG_DIST_DP);
    }

private boolean isRTL() {
        return TextUtilsCompat.getLayoutDirectionFromLocale(Locale.getDefault()) == LayoutDirection.RTL;
    }
`

**Comment by yarolegovich** [comment]
@WiiliamChik is right, but there's absolutely no need in editing the source code, just use your method to pass a correct value to the builder:
```java
new SlidingRootNavBuilder(this)
  .withGravity(isRtl() ? SlideGravity.RIGHT : SlideGravity.LEFT)
  ...
  .inject();
```

**Comment by mwshubham** [comment]
need to move from https://github.com/PSD-Company/duo-navigation-drawer because of RTL support hope this work well. . . .  Hoping for best !
