### ISSUE TITLE
Proper OnResume Behavior Suggestions? 

### ISSUE THREAD

**Issue by searchy2** [yarolegovich/SlidingRootNav#34]
I love this library so much! :heart: 

A quick question on the proper way to handle SlidingRootNav's lifecycle. When an activity using SlidingRootNav is recreated (resumed from sleep), should the menu be recreated? I have noticed that if the menu is open and the app is put to sleep and then resumed, the menu stays open but the sliding mechanism no longer works. 

Thank you for your suggestions!

**Comment by yarolegovich** [comment]
Honestly, I'm confused. What exactly leads to this? Do you turn the screen off and on, or do you restore activity from activity stack, does it happen after orientation changes?

**Comment by searchy2** [comment]
Sorry about the confusion. The navigation menu gets stuck in the open position when the activity is resumed. 
Steps to reproduce:
1. Open SlidingRootNav. 
2. Switch to other apps. Open enough apps so that Android puts your app to sleep. 
3. Open your app from the recents drawer. When your app is resumed, the menu is open and cannot be closed. 

I initialize SlidingRootNav in onCreate. Should it also be initialized in onResume too?

**Comment by abeemukthees** [comment]
```
override fun onResume() {
        super.onResume()
        if (slidingRootNav.isMenuOpened) slidingRootNav.closeMenu()
    }
```

**Comment by searchy2** [comment]
Closing the sliding menu is the right way to go. I think closing it on pause is better than hiding it on resume.
