### ISSUE TITLE
Whether support the menus to open from the right side

### ISSUE THREAD

**Issue by BobEve** [yarolegovich/SlidingRootNav#35]
Whether support the menus to open from the right side？
thanks

**Comment by AniketBito** [comment]
Yes it supports.
Try  .withGravity(SlideGravity.RIGHT)

**Comment by yarolegovich** [comment]
The answer above is correct, all methods with their explanations are listed in [the docs](https://github.com/yarolegovich/SlidingRootNav#menu-behavior).
