### ISSUE TITLE
How to make oldRoot to be maximized when clicked

### ISSUE THREAD

**Issue by sgallego** [yarolegovich/SlidingRootNav#37]
Hi,
when menu is opened and oldRoot is minimized. Is there any way to get this fragment maximized on click?
Thanks a lot for your library!

**Comment by sgallego** [comment]
Finally I solve it out of the library adding a view on top of the root view. When the view is clicked the menu is closed.

        clickConsumer.setOnClickListener {
            slidingRootNav?.closeMenu()
        }

I listen to drag changes to show or hide the added view:

        override fun onDragEnd(isMenuOpened: Boolean) {
            clickConsumer.visibility = if(isMenuOpened) View.VISIBLE else View.GONE
        }

**Comment by ZeroCool00** [comment]
how to use onDragEnd method.., i mean how did you override this method.. i have a same issue.
