### ISSUE TITLE
Changing font type and size

### ISSUE THREAD

**Issue by ivanfwc** [yarolegovich/SlidingRootNav#39]
Hi! I would like to ask that, is it possible to change the font size and font type? I've been looking for this issue quite a while but still couldn't find it. Any help would be much obliged.

**Comment by yarolegovich** [comment]
The library has nothing to do with appearance of UI elements. Explore [the sample app](https://github.com/yarolegovich/SlidingRootNav/tree/master/sample/src/main) and check how I define [menu items](https://github.com/yarolegovich/SlidingRootNav/blob/master/sample/src/main/res/layout/item_option.xml).
