### ISSUE TITLE
Allow back button click when withContentClickableWhenMenuOpened is set to false

### ISSUE THREAD

**Issue by santalu** [yarolegovich/SlidingRootNav#41]
I'd like to click back button and close menu even though i set `withContentClickableWhenMenuOpened(false)`

**Comment by yarolegovich** [comment]
Then you need to handle other click consumption yourself.  Put an instance of [this class](https://github.com/yarolegovich/SlidingRootNav/blob/master/library/src/main/java/com/yarolegovich/slidingrootnav/util/HiddenMenuClickConsumer.java) above your content, such that it doesn't cover your toolbar.
