### ISSUE TITLE
Slow application

### ISSUE THREAD

**Issue by thair-jaber** [yarolegovich/SlidingRootNav#43]
Hello,

I'm using this amazing library, but i'v noticed that my home activity is too slow and there is lag in this activity while this activity has a view pager with tow fragments only.

Is there any thing you can help me to find the issue?
Thanks in advance.

**Comment by yarolegovich** [comment]
Try using [android profiler](https://developer.android.com/studio/profile/android-profiler.html) to determine weak spots of the app.

**Comment by anandshivam44** [comment]
I'm facing similar issue
