### ISSUE TITLE
open a new activity when sliding is closed

### ISSUE THREAD

**Issue by janvalji** [yarolegovich/SlidingRootNav#76]
@yarolegovich   I've reviewed your answer, but that's not enough. I want to open a new activity when clicked, but the sliding remains open

https://github.com/yarolegovich/SlidingRootNav/issues/1

> Code here: https://pastebin.pl/view/c264d21b

`  layout_user.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                slidingRootNav.closeMenu(true);
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        startActivity(new Intent(context, UserActivity.class));
                    }
                }, 300);

            }
        });`

**Comment by gordonfreemanix** [comment]
> I've reviewed your answer, but that's not enough. I want to open a new activity when clicked, but the sliding remains open
> 
> #1
> 
> `
> 
> layout_user.setOnClickListener(new View.OnClickListener() {
> @override
> public void onClick(View v) {
> slidingRootNav.closeMenu(true);
> new Handler().postDelayed(new Runnable() {
> @override
> public void run() {
> startActivity(new Intent(context, UserActivity.class));
> }
> }, 300);
> 
> ```
>         }
>     });
> ```
> 
> `
