### ISSUE TITLE
withRootViewElevation

### ISSUE THREAD

**Issue by GuntarsLuta** [yarolegovich/SlidingRootNav#8]
withRootViewElevation not working

**Comment by yarolegovich** [comment]
It is not supposed to work on pre-lollipop devices.

**Comment by GuntarsLuta** [comment]
not working on 6.0.1

**Comment by yarolegovich** [comment]
It just doesn't draw the shadow? Show your code. 
Does the sample work?

**Comment by GuntarsLuta** [comment]
Sample works right.

```
        mSlidingRootNav = new SlidingRootNavBuilder(this)
                .withToolbarMenuToggle(toolbar)
                .withMenuOpened(true)
                .withSavedState(savedInstanceState)
                .withMenuLayout(R.layout.menu_drawer)
                .inject();
```

Is there other any trick?

**Comment by yarolegovich** [comment]
Seems like everything is correct. Can you make a screenshot?

**Comment by GuntarsLuta** [comment]
![screenshot_2017-04-25-19-44-13](https://cloud.githubusercontent.com/assets/8680804/25397136/dcff885c-29ef-11e7-89c0-27a71efe45a4.png)

**Comment by yarolegovich** [comment]
Try setting `android:background` attribute to some color on the root element of your `R.layout.menu_drawer`.

**Comment by GuntarsLuta** [comment]
Already has

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/menuContent"
    android:layout_width="@dimen/menu_width"
    android:layout_height="match_parent"
    android:background="@color/app_theme"
    android:orientation="vertical" >
```

**Comment by yarolegovich** [comment]
Oh, I was wrong. To the root element of layout that you set using `setContentView` in your activity.

**Comment by GuntarsLuta** [comment]
Jup it worked, thank you :) 👍
